#!/bin/sh

echo "To update firmware......"

VERSION=1.3.0
echo "The current version is $VERSION"

cd /home/root
echo "remove old files......"
rm -f BOOT0002.BIN image.ub rootfs.cpio

echo "extracting the bin file......"
filename=cornetnetwork.bin
if [ -e $filename ]; then 
	echo "$filename does exist!"
else
	echo "$filename not exist yet!"
	exit 2
fi
tar -tvf cornetnetwork.bin
tar -xzvf cornetnetwork.bin

echo "copying......"
filename=BOOT0002.BIN
if [ -e $filename ]; then 
	echo "$filename does exist!"
else
	echo "$filename not exist yet!"
	exit 3
fi
filename=image.ub
if [ -e $filename ]; then 
	echo "$filename does exist!"
else
	echo "$filename not exist yet!"
	exit 4
fi
filename=rootfs.cpio
if [ -e $filename ]; then 
	echo "$filename does exist!"
else
	echo "$filename not exist yet!"
	exit 5
fi
cp BOOT0002.BIN image.ub /run/media/mmcblk0p1
sync
cd /run/media/mmcblk0p5
if [ $? -eq 0 ]; then
	echo "/run/media/mmcblkp5 does exist! It's RAM-booting mode now!"
	cp rootfs.cpio  /run/media/mmcblk0p5
else
	echo "/run/media/mmcblkp5 does not exist! It's SDCard-booting mode now! Go to root!"
	cp rootfs.cpio /
	cd /
fi
sync

echo "extracting rootfs......"
cpio -idumv < rootfs.cpio
sync

cd /home/root
echo "remove cornetnetwork.bin......"
rm -f cornetnetwork.bin
sync

echo "finished!"
exit 1


